### ISSUE TITLE
runner 2.309.0 apparently runs on mac-10.13, but includes incompatible node binary

### ISSUE THREAD

**Issue by chickenandpork** [actions/runner#2879]
**Describe the bug**
The runner claims compatibility with MacOS-10.13 and later.  The tarball seems to include a node binary that doesn't share the same compatibility with macos-10.13.

**To Reproduce**
1. go into a Mac OS intel box running 10.13 (latest is 10.13.6 in that line)
2. install normally: unpack, ./config.sh, ./run.sh
3. Use this runner in a build
4. Witness the error in the node binary (failed after 7 seconds, this is the first line of the build output):
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/actions-runner/externals/node20/bin/node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

The part that makes me super-accusatory is "was built for Mac OS X 10.15", which may imply "won't work in the 10.13 that runner seems to support"
 
**Expected behavior**
Expected typical build job: build is picked up, built, happily completed.

## Runner Version and Platform
runner-2.309.0

OS of the machine running the runner? OSX/Windows/Linux/...
intel mac (Macmini5,3) running macOS 10.13.6 (17G14042)

## What's not working?
It seems though the work is done via a node v20 process included in the runner archive; this `node` binary does not support Mac-10.13, which seems an oversight: Runner claims to support macOS-10.13.
<img width="900" alt="Screenshot 2023-09-24 at 02 09 09" src="https://github.com/actions/runner/assets/2320540/5d8bf450-d861-4885-b2c7-c77b6ab1cb06">

## Job Log Output
(runner tarball unpacked into `/usr/local/actions-runner`)
```
Run actions/checkout@v4
  with:
    repository: XXXXXXXX
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true
  env:
    HTTP_PROXY: XXXXXXXX
    HTTPS_PROXY: XXXXXXXX
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/actions-runner/externals/node20/bin/node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/actions-runner/externals/node20/bin/node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by thboop** [comment]
Hey @chickenandpork, in order to evolve the security of the Actions ecoysystem, we are moving towards node 20. Node16 has reached the end of its life. You can read about that effort [here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).  Sadly High Sierra does not support node 20, and is no longer supported by Apple. We have a planned date to disable Node 16 in Spring of 2024, we would strongly encourage you to update your macos version before that time.


For now, reverting to the v3 version of checkout should solve your issue, as v4 is node20.

**Comment by bryanmacfarlane** [comment]
This may not be accurate anymore:

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#macos

**Comment by chickenandpork** [comment]
PR up over in docs FYI ..  https://github.com/github/docs/pull/28488
