### ISSUE TITLE
Current runner version: '2.331.0' : Cannot find module 'node:process'

### ISSUE THREAD

**Issue by sharmam-caremonitor** [actions/runner#4199]
Suddenly out  apps are throwing error getting build using 2.331.0 version. They were working fine on 2.330.0 

node 14 version

**Comment by TingluoHuang** [comment]
any info about what error you get?

**Comment by sharmam-caremonitor** [comment]
module not found  errors node:process  . Seems to be node related issues

**Comment by sharmam-caremonitor** [comment]
Cannot find module 'node:process' Error being received
